### ISSUE TITLE
Serviço de atualização de dados do tipo de usuário

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#10]
- [x] Criação do serviço com a rotina de atualização de dados do usuário;

**Informar o caminho e o nome do serviço**

**Comment by AyaneYamassaki** [comment]
- Foi criado o serviço de atualização de tipos de usuários da tabela "tipo", juntamente com o serviço de inclusão do mesmo.

**Caminho: GerenciadorEventoEtec/src/tipo-usuario/model/save-tipo.php**
