### ISSUE TITLE
Serviço para exlusão de tipo de usuários

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#11]
- [x] Criação do serviço para rotina de exclusão de dados no banco

**Informar o caminho e nome do serviço**

**Comment by AyaneYamassaki** [comment]
- Foi criado o serviço de exclusão de tipos de usuários da tabela "tipo"

**Caminho: GerenciadorEventoEtec/src/tipo-usuario/model/delete-tipo.php**
