### ISSUE TITLE
Criação da conexão com o banco de dados do projeto

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#12]
Programação do serviço de conexão com o banco de dados em php.

**Informar o caminho e nome do serviço**

**Comment by AyaneYamassaki** [comment]
Segue a baixo os dados do banco de dados 3762242_elevent:

![Captura de ecrã 0003-04-27, às 13 19 41](https://user-images.githubusercontent.com/61321109/116276951-64352880-a75b-11eb-8ae1-2349aeea950a.png)

**Caminho:** http://elevent.myartsonline.com/src/conexao/cone.php
**Serviço:** PDO

**Comment by AyaneYamassaki** [comment]
Caminho:  GerenciadorEventoEtec/src/conexao/cone.php

Foi realizado o processo de conexão com o banco de dados "3762242_elevent", utilizando a extensão PDO.

**Comment by AyaneYamassaki** [comment]
Caminho: GerenciadorEventoEtec/src/conexao/cone.php

Foi realizado o processo de conexão com o banco de dados "epiz_28910013_elevent", utilizando a extensão PDO.

Dados do banco de dados...
    $hostname= "sql303.epizy.com";
    $dbname= "epiz_28910013_elevent";
    $username= "epiz_28910013";
    $password= "Etectcc2021";

**Comment by AyaneYamassaki** [comment]
Caminho: GerenciadorEventoEtec/src/conexao/cone.php

Foi realizado o processo de conexão com o banco de dados "epiz_28910013_elevent", utilizando a extensão PDO.

Dados do banco de dados...
    $hostname= "sql303.epizy.com";
    $dbname= "epiz_28910013_elevent";
    $username= "epiz_28910013";
    $password= "Etectcc2021";
