### ISSUE TITLE
Integração do serviço e tela de atualização de dados do tipo de usuário

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#14]
- [x]  Desenvolvimento da integração do serviço de atualização de tipo de usuários com a tela.

- [x]  **Tem que existir um retorno em tela para o usuário do sistema sobre o que está acontecendo.**

**Comment by AyaneYamassaki** [comment]
- Foi criada a integração do serviço de atualização de tipos de usuários da tabela "tipo"
- O retorno em tela para o usuário será realizado pelo SweetAlert

**Caminho: GerenciadorEventoEtec/src/tipo-usuario/controller/edit-tipo.js**
