### ISSUE TITLE
Integração do serviço e tela de listagem de dados do tipo de usuário

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#15]
- [x]  Desenvolvimento da integração do serviço de listagem de tipo de usuários com a tela.

- [x]  **Tem que existir um retorno em tela para o usuário do sistema sobre o que está acontecendo.**

**Comment by AyaneYamassaki** [comment]
Foi criada a integração do serviço de listagem de tipos de usuários da tabela "tipo"

**Caminho:** GerenciadorEventoEtec/src/tipo-usuario/controller/list-tipo.js
