### ISSUE TITLE
Integração do serviço e tela de exclusão de dados do tipo de usuário

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#16]
- [x] Desenvolvimento da integração do serviço de exclusão de tipo de usuários com a tela.

 **

- [x] Tem que existir um retorno em tela para o usuário do sistema sobre o que está acontecendo.

**

**Comment by AyaneYamassaki** [comment]
- Foi criada a integração do serviço de exclusão de tipos de usuários da tabela "tipo"
- O retorno em tela para o usuário será realizado pelo SweetAlert

**Caminho: GerenciadorEventoEtec/src/tipo-usuario/controller/delete-tipo.js**
