### ISSUE TITLE
Criar os arquivos iniciais do projeto

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#2]
Gerar o commit inicial do projeto, bem como todas as bibliotecas que serão utilizadas dentro do projeto.

**Comment by Yuri-sc** [comment]
Todos os arquivos iniciais: 

- Sweet alert
- Material Design Icons
- Bootstrap
- Jquery 3.5.1
- Index.html

Todos foram adicionados.

**Comment by aocastro** [comment]
**DEVIDAMENTE CONFERIDO E VALIDADO**
