### ISSUE TITLE
Criar um domínio/hospedagem gratuita para o projeto

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#3]
Gerar uma hospedagem do tipo gratuita para o projeto, lembrando que o mesmo deverá respeitar minimamente o nome oficial do sistema.

**Comment by Nick061293** [comment]
Foi configurado:

- SFTP;
- Domínio gratuito utilizando o AwardSpace;
- Domínio: elevent.myartsonline.com

**Comment by aocastro** [comment]
**Somente a nível de documentação, poste aqui os dados para acesso FTP e IP do banco de dados criado.**

**Comment by Nick061293** [comment]
Dados para acesso FTP - https://user-images.githubusercontent.com/61321087/112976149-e0bbf380-912a-11eb-8bb6-b468c898f3fc.png

**Comment by AyaneYamassaki** [comment]
Foi realizado alterações do site de hospedagem:
awardspace → infinityfree
Dados do SFTP...
{
    "name": "elevent-etec.infinityfreeapp.com",
    "context": "/Users/karenayanepascoalyamassaki/TCC/GerenciadorEventoEtec",
    "protocol": "ftp",
    "host": "ftpupload.net",
    "port": 21,
    "username": "epiz_28910013",
    "password": "Etectcc2021",
    "remotePath": "/htdocs",
    "connectTimeout": 10000,
    "uploadOnSave": true,
    "downloadOnOpen": false,
    "syncMode": "update",
    "ignore": []
}
