### ISSUE TITLE
Criação do banco de dados do projeto.

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#4]
Desenvolvimento do banco de dados do projeto.

**Comment by AyaneYamassaki** [comment]
![Gerenciador de Eventos da Etec de Lins](https://user-images.githubusercontent.com/61321109/112368297-afba6980-8cb9-11eb-8b5b-1f3e0bb33eef.png)

**Comment by aocastro** [comment]
**OBSERVAÇÃO**

_A entidade de [participante] não tem relacionamento com login, pois os dados do login são atributos da entidade [participante]_

**Na entidade [participante] tente criar um ID para o mesmo, não use o CPF, porque se for usar o mesmo corremos o risco de ter que criar uma rotina de validação do mesmo, que é algo não tão simples e é um tipo de documento que nos traz muitos problemas no armazenamento do já que existe uma lei regulamentadora para o do mesmo o LGPD**

_**Revise todas as entidades, pois existem algumas que contém atributo iniciando com letra maíscula e isso não pode ocorrer, pois existe uma convenção para como criar atributos, exemplo:
nomeCompleto
nome_completo**_

**Comment by AyaneYamassaki** [comment]
Foi realizado, a análise novamente do banco de dados, chegando a conclusão onde 
- Alteramos os início dos atributos no formato relatado no exemplo da observação(nomeCompleto);
- Excluimos a tabela "login"
- Adicionamos o atributo "id"(solicitado na observação) e"senha"(que estava na tabela "login") na tabela "participante"

![Captura de ecrã 0003-03-25, às 11 41 02](https://user-images.githubusercontent.com/61321109/112491558-307f7100-8d5f-11eb-9c06-9ba5a6d7dab4.png)

**Comment by aocastro** [comment]
**VAMOS AS CORREÇÕES**

1. A entidade "possui" não faz sentido, seria mais interessante chamar ela de "inscricao" e adicionar o atributo data e hora de inscrição
2. A entidade "tipo" para participantes não tem os atributos palestrante/volutário/visitante, esses são resultados lógicos, na verdade voc}e somente precisa de um atributo para guardar essas variantes.

**Comment by AyaneYamassaki** [comment]
Foi realizado, a correção do banco de dados, de acordo com as instruções onde
- Alteramos o nome da tabela "possui" para "inscricao"
- Adicionamos os atributos "dataInscricao" e "horaInscricao"na tabela "tipo"
- Excluimos os atributos "palestrante", "voluntario" e "visitante" da tabela "tipo" 
- Adicionamos o atributo "nomeTipo" na tabela "tipo"

![Alteração 29 03](https://user-images.githubusercontent.com/61321109/112978339-98520500-912d-11eb-9398-fbcb85e2cb03.png)

**Comment by aocastro** [comment]
A tabela endereco, iremos tirar o atributo número dele, pois iremos adicionar o CEP e trabalhar com serviço externo para preenchimento dos campos, ou seja, o CEP e número do imóvel deverá ficar no forncedor e não mais na tabela endereço.

**Na tabela endereço somente iremos armazenar aquelas ruas que não tem cep definido.**

**Comment by AyaneYamassaki** [comment]
Foi realizada as alterações compreendidas durante a reunião:
![TCC](https://user-images.githubusercontent.com/61321109/113758951-e1d0c000-96ea-11eb-8013-41e3ed56d902.png)

**Comment by aocastro** [comment]
Muito bom o banco de dados ficará em standy-by aguardando novas implementações.

**Comment by AyaneYamassaki** [comment]
Atualizações realizadas até o momento no banco de dados...
![atual](https://user-images.githubusercontent.com/61321109/133480867-f3600c4e-0149-42b0-8e48-dba09641c635.png)
