### ISSUE TITLE
Proposta de tela inicial do sistema

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#5]
Criar uma proposta de tela inicial do sistema, sempre tendo em vista as possibilidades da responsividade e layout limpo e direto.

**Comment by Yuri-sc** [comment]
Proposta de tela inicial do sistema finalizada com sucesso.
Site: http://elevent.myartsonline.com/

https://user-images.githubusercontent.com/61591966/113024464-272a4600-915d-11eb-980c-0f4d62588e8c.mov
