### ISSUE TITLE
Criação da estrutura de pastas do projeto

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#6]
Criação da estrutura organizacional do projeto, visando a metodologia MVC

**Comment by Yuri-sc** [comment]
Foi criado a pasta "src" e dentro dela a estrutura organizacional das seguintes pastas:

- checklist
- evento
- fornecedor
- participante

E dentro delas a metodologia MVC.

**Comment by Yuri-sc** [comment]
![image](https://user-images.githubusercontent.com/61591966/113755951-42f69480-96e7-11eb-8f4c-9d10b4ecf9bf.png)

**Comment by aocastro** [comment]
A estrutura apresentada, está validada para o processo de desenvolvimento.
