### ISSUE TITLE
Criação da tela para gerenciamento do tipo de usuário

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#7]
Para o desenvolvimento deste se faz necessário se atentar aos aspectos do CRUD, ou seja a tela tem deter a possibilidade de inclusão, atualização, exclusão e listagem de registros.

- [x] Inclusão
- [x] Atualização
- [x] Listagem
- [x] Exclusão

**Comment by AyaneYamassaki** [comment]
**Caminho: GerenciadorEventoEtec/src/tipo-usuario/view/list-tipo.html**
**Caminho: GerenciadorEventoEtec/src/tipo-usuario/view/form-tipo.html**
