### ISSUE TITLE
Serviço de inclusão de tipo de usuário

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#8]
- [x] Criação do serviço em PHP para inclusão de usuários.

**Informar o local e nome do serviço.**

**Comment by AyaneYamassaki** [comment]
Foi criado o serviço de inclusão de tipos de usuários da tabela "tipo"

**Caminho: GerenciadorEventoEtec/src/tipo-usuario/model/save-tipo.php**
