### ISSUE TITLE
Serviço de listagem de usuário

### ISSUE THREAD

**Issue by aocastro** [aocastro/GerenciadorEventoEtec#9]
- [x] Criação do serviço de listagem de registros do banco de dados quanto ao tipo de usuário.

**Informar o caminho e nome do serviço**

**Comment by AyaneYamassaki** [comment]
Foi criado o serviço de listagem de tipos de usuários da tabela "tipo"

**Caminho:** GerenciadorEventoEtec/src/tipo-usuario/model/list-tipo.php
